---
- name: install apache
  hosts: prod
  become: yes

  tasks: 
  - name: install apache web server
    yum:  name=httpd state=latest
    
  - name: start apache service and enable on reboot
    service: name=httpd state=started enabled=yes
    
