---
- name: run the loop
  hosts: prodaction
  become: yes
  
  tasks:
  - name: task1
    debug: msg="hello {{ item }}"
    loop:
    - "user1"
    - "user2" 

  - name: until task
    shell: echo -n Z >> until.txt && cat until.txt
    register: output1
    delay: 3
    retries: 10
    until: output1.stdout.find("ZZZZ") == false

  - name: print output
    debug:
      var: output1.stdout

  - name: install app
    yum: name={{ item }} state=installed
    loop:
    - nano
    - tree
